# Project information
site_name: Meu Micro
site_url: https://meumicro.github.io
site_author: Kleber Santos
site_description: >-
  Escrevendo a documentação de uma forma masi facil com markdown

# Repository
repo_name: meumicro.github.io
repo_url: https://github.com/MeuMicro/meumicro.github.io

# Copyright
copyright: Copyright &copy; 2023 - MeuMicro

# Page tree
nav:
        - Inicio: index.md
        #- Blog:
        #        - blog/index.md
        - Hardware:
          - Manutenção preventiva e corretiva: hardware/manutencao.md
          - Venda de Peças e Partes: hardware/venda.md
        - Software:
          - Licencimento Microsoft: software/microsoft.md
          - Sistemas Open-Source: software/opensource.md
          - Serviços especializados: software/servicos.md
        - Segurança da Informação:
          - Conceitos básicos da segurança:  infosec/seguranca.md
          - Malware: infosec/malware.md
        - Perguntas Frequentes: faq.md
        - Sobre: 
                - Ajuda: sobre/about.md
                - A empresa: sobre/empresa.md


# Configuration
theme:
        name: material
        custom_dir: overrides
        language: pt-BR
        icon:
                logo: fontawesome/solid/computer
        features:
                - announce.dismiss
                #- content.action.edit
                #- content.action.view
                - content.code.annotate
                - content.code.copy
                # - content.tabs.link
                - content.tooltips
                # - header.autohide
                - navigation.expand
                #- navigation.footer
                - navigation.indexes
                # - navigation.instant
                # - navigation.prune
                #- navigation.sections
                #- navigation.tabs
                # - navigation.tabs.sticky
                - navigation.top
                - navigation.tracking
                - search.highlight
                - search.share
                - search.suggest
                - toc.follow
                # - toc.integrate
        palette:
                - scheme: default
                  primary: indigo
                  accent: indigo
                  toggle:
                    icon: material/brightness-7
                    name: Switch to dark mode
                - scheme: slate
                  primary: indigo
                  accent: indigo
                  toggle:
                    icon: material/brightness-4
                    name: Switch to light mode
        font:
                text: Roboto
                code: Roboto Mono
        #favicon: assets/favicon.png
        #icon:
        #        logo: logo

# Customization
extra:
        analytics:
                provider: google
                property: !ENV GOOGLE_ANALYTICS_KEY
        social:
                - icon: fontawesome/brands/github
                  link: https://github.com/meumicro
        #         - icon: fontawesome/brands/instagram
        #           link: https://www.instagram.com/meumicro/
        #         - icon: fontawesome/brands/youtube
        #           link: https://www.youtube.com/channel/meumicro
        #         - icon: fontawesome/brands/linkedin
        #           link: https://www.linkedin.com/company/meumicro
        #         - icon: fontawesome/brands/facebook
        #           link: https://www.facebook.com/meumicro
        consent:
                title: Consentimento de cookies
                description: >- 
                        Usamos cookies para reconhecer suas visitas e preferências repetidas, bem como para medir a eficácia de nossa documentação e se os usuários encontram o que procuram. Com o seu consentimento, você está nos ajudando a melhorar nossa documentação.Usamos cookies para reconhecer suas visitas e preferências repetidas, bem como para medir a eficácia de nossa documentação e se os usuários encontram o que procuram. Com o seu consentimento, você está nos ajudando a melhorar nossa documentação.
                actions:
                        - accept 
                        - reject 
        caption: true
        lazy_load: true
        align: center

# CSS
extra_css:
        - 'assets/css/extra.css'


# Plugins
plugins:
        - search:
                lang: pt
        - minify:
                minify_html: true

# Extensions
markdown_extensions:
        - abbr
        - admonition
        - attr_list
        - def_list
        - footnotes
        - md_in_html
        #- toc:
        #        permalink: true
        - pymdownx.arithmatex:
                generic: true
        - pymdownx.betterem:
                smart_enable: all
        - pymdownx.caret
        - pymdownx.details
        - pymdownx.emoji:
                emoji_generator: !!python/name:materialx.emoji.to_svg
                emoji_index: !!python/name:materialx.emoji.twemoji
        - pymdownx.highlight:
                anchor_linenums: true
                line_spans: __span
                pygments_lang_class: true
        - pymdownx.inlinehilite
        - pymdownx.keys
        - pymdownx.magiclink:
                repo_url_shorthand: true
                user: meumicro
                repo: meumicro.github.io
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences:
                custom_fences:
                - name: mermaid
                  class: mermaid
                  format: !!python/name:pymdownx.superfences.fence_code_format
        - pymdownx.tabbed:
                alternate_style: true
        - pymdownx.tasklist:
                custom_checkbox: true
        - pymdownx.tilde
        
